version: "2"

services:

  backstopjs:
    image: backstopjs/backstopjs
    volumes:
      - .:/src

  web:
    image: fpfis/php56-dev
    working_dir: /var/www/html
    ports:
      - 8888:8080
    volumes:
      - .:/var/www/html
    environment:
      DOCUMENT_ROOT: /var/www/html/build

  mysql:
    image: fpfis/mysql56
